server:
  port: 8888

management:
  endpoints.web.exposure.include: 'prometheus, health'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
